# Generated by Django 4.0a1 on 2021-10-16 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpost',
            name='content',
            field=models.CharField(max_length=512),
        ),
    ]
